kind: Deployment
apiVersion: apps/v1
metadata:
  name: portal-inventario-frontend-deployment
  namespace: dev-front-oss
  labels:
    app: portal-inventario-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portal-inventario-frontend
  template:
    metadata:
      labels:
        app: portal-inventario-frontend
    spec:
      containers:
        - name: portal-inventario-frontend-container
          image: image-registry.openshift-image-registry.svc:5000/dev-front-oss/portal-inventario-frontend:latest
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            requests:
              memory: "200Mi"
              cpu: "20m"
