import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { getTelefonicaSkin, ThemeContextProvider } from "@telefonica/mistica";
import "@telefonica/mistica/css/mistica.css";
import "material-symbols";
import { Toaster } from "@/components/ui/toaster";
import Link from "next/link";
import GlobalModal from "@/components/GlobalModal";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Portal Inventario",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased w-full h-full absolute top-0 left-0 bg-[#eee]`}
      >
        <ThemeContextProvider
          theme={{
            skin: getTelefonicaSkin(),
            i18n: { locale: "es-ES", phoneNumberFormattingRegionCode: "ES" },
            colorScheme: "light",
            Link: { type: "Next14", Component: Link },
          }}
        >
          {children}
          <GlobalModal />
          <Toaster />
        </ThemeContextProvider>
      </body>
    </html>
  );
}
